version: '3'

services:
  tomee:
    image: pravrang/tomee7.0
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: ingress
      - target: 8009
        published: 8009
        protocol: tcp
        mode: ingress
    volumes:
      - "vol_logs:/opt/tomee/webapps"
      - "vol_logs:/opt/tomee/logs"
      - "vol_logs:/opt/shared" 
    networks:
      docker1:
        aliases:
          - tomee
    dns_search: webmidlabs.com

    deploy:
      replicas: 2
    update_config:
      parallelism: 2
      delay: 10s
    restart_policy:
      condition: on-failure

  httpd:
    image: pravrang/httpd2.4.25
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress
      
    volumes:
      - "vol_logs:/opt/httpd/logs"
      - "vol_logs:/opt/shared" 
    networks:
      docker1:
        aliases:
          - httpd
    dns_search: webmidlabs.com

    deploy:
      replicas: 2
    update_config:
      parallelism: 2
      delay: 10s
    restart_policy:
      condition: on-failure

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "9080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

volumes:
  vol_logs:

networks:
  docker1:

  
