version: '3'

services:
  tomee:
    image: pravrang/tomee7.0
    name: tomee
    ports:
      - "8080:8080"
      - "8009:8009"
      - "8443:8443"
    volumes:
      - "vol_logs:/opt/tomee/webapps"
      - "vol_logs:/opt/tomee/logs"
      - "vol_logs:/opt/shared" 
    networks:
      frontend:
        aliases:
          - tomee
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "9080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

  httpd:
    image: pravrang/httpd2.4.25
    ports:
      - "80:80"
      - "443:443"    
    volumes:
      - "vol_logs:/opt/httpd/logs"
      - "vol_logs:/opt/shared" 
    networks:
      frontend:
        aliases:
          - httpd
    dns_search: webmidlabs.com
    depends_on:
      - tomee
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s

volumes:
  vol_logs:

networks:
  docker1:

  
